// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Seq                  uint64            `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Timestamp            uint64            `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload              []byte            `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Meta                 map[string][]byte `protobuf:"bytes,4,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Message) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Message) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetMeta() map[string][]byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

type MessageWithRoute struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageWithRoute) Reset()         { *m = MessageWithRoute{} }
func (m *MessageWithRoute) String() string { return proto.CompactTextString(m) }
func (*MessageWithRoute) ProtoMessage()    {}
func (*MessageWithRoute) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *MessageWithRoute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithRoute.Unmarshal(m, b)
}
func (m *MessageWithRoute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithRoute.Marshal(b, m, deterministic)
}
func (m *MessageWithRoute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithRoute.Merge(m, src)
}
func (m *MessageWithRoute) XXX_Size() int {
	return xxx_messageInfo_MessageWithRoute.Size(m)
}
func (m *MessageWithRoute) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithRoute.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithRoute proto.InternalMessageInfo

func (m *MessageWithRoute) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *MessageWithRoute) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type MessagesBatchRequest struct {
	Messages             []*MessageWithRoute `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MessagesBatchRequest) Reset()         { *m = MessagesBatchRequest{} }
func (m *MessagesBatchRequest) String() string { return proto.CompactTextString(m) }
func (*MessagesBatchRequest) ProtoMessage()    {}
func (*MessagesBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *MessagesBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagesBatchRequest.Unmarshal(m, b)
}
func (m *MessagesBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagesBatchRequest.Marshal(b, m, deterministic)
}
func (m *MessagesBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesBatchRequest.Merge(m, src)
}
func (m *MessagesBatchRequest) XXX_Size() int {
	return xxx_messageInfo_MessagesBatchRequest.Size(m)
}
func (m *MessagesBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesBatchRequest proto.InternalMessageInfo

func (m *MessagesBatchRequest) GetMessages() []*MessageWithRoute {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Error struct {
	Code                 uint64   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MessagesBatchResponse struct {
	Error                *Error            `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ConsumedSeqs         map[string]uint64 `protobuf:"bytes,2,rep,name=consumedSeqs,proto3" json:"consumedSeqs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	ProducedSeqs         map[string]uint64 `protobuf:"bytes,3,rep,name=producedSeqs,proto3" json:"producedSeqs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MessagesBatchResponse) Reset()         { *m = MessagesBatchResponse{} }
func (m *MessagesBatchResponse) String() string { return proto.CompactTextString(m) }
func (*MessagesBatchResponse) ProtoMessage()    {}
func (*MessagesBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *MessagesBatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagesBatchResponse.Unmarshal(m, b)
}
func (m *MessagesBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagesBatchResponse.Marshal(b, m, deterministic)
}
func (m *MessagesBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesBatchResponse.Merge(m, src)
}
func (m *MessagesBatchResponse) XXX_Size() int {
	return xxx_messageInfo_MessagesBatchResponse.Size(m)
}
func (m *MessagesBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesBatchResponse proto.InternalMessageInfo

func (m *MessagesBatchResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *MessagesBatchResponse) GetConsumedSeqs() map[string]uint64 {
	if m != nil {
		return m.ConsumedSeqs
	}
	return nil
}

func (m *MessagesBatchResponse) GetProducedSeqs() map[string]uint64 {
	if m != nil {
		return m.ProducedSeqs
	}
	return nil
}

type GetLastMessageRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLastMessageRequest) Reset()         { *m = GetLastMessageRequest{} }
func (m *GetLastMessageRequest) String() string { return proto.CompactTextString(m) }
func (*GetLastMessageRequest) ProtoMessage()    {}
func (*GetLastMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *GetLastMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLastMessageRequest.Unmarshal(m, b)
}
func (m *GetLastMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLastMessageRequest.Marshal(b, m, deterministic)
}
func (m *GetLastMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLastMessageRequest.Merge(m, src)
}
func (m *GetLastMessageRequest) XXX_Size() int {
	return xxx_messageInfo_GetLastMessageRequest.Size(m)
}
func (m *GetLastMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLastMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLastMessageRequest proto.InternalMessageInfo

func (m *GetLastMessageRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type GetLastMessageResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Message              *Message `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLastMessageResponse) Reset()         { *m = GetLastMessageResponse{} }
func (m *GetLastMessageResponse) String() string { return proto.CompactTextString(m) }
func (*GetLastMessageResponse) ProtoMessage()    {}
func (*GetLastMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *GetLastMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLastMessageResponse.Unmarshal(m, b)
}
func (m *GetLastMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLastMessageResponse.Marshal(b, m, deterministic)
}
func (m *GetLastMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLastMessageResponse.Merge(m, src)
}
func (m *GetLastMessageResponse) XXX_Size() int {
	return xxx_messageInfo_GetLastMessageResponse.Size(m)
}
func (m *GetLastMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLastMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLastMessageResponse proto.InternalMessageInfo

func (m *GetLastMessageResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *GetLastMessageResponse) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type GetNextMessageRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Seq                  uint64   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNextMessageRequest) Reset()         { *m = GetNextMessageRequest{} }
func (m *GetNextMessageRequest) String() string { return proto.CompactTextString(m) }
func (*GetNextMessageRequest) ProtoMessage()    {}
func (*GetNextMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *GetNextMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNextMessageRequest.Unmarshal(m, b)
}
func (m *GetNextMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNextMessageRequest.Marshal(b, m, deterministic)
}
func (m *GetNextMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNextMessageRequest.Merge(m, src)
}
func (m *GetNextMessageRequest) XXX_Size() int {
	return xxx_messageInfo_GetNextMessageRequest.Size(m)
}
func (m *GetNextMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNextMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNextMessageRequest proto.InternalMessageInfo

func (m *GetNextMessageRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *GetNextMessageRequest) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type GetNextMessageResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Message              *Message `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNextMessageResponse) Reset()         { *m = GetNextMessageResponse{} }
func (m *GetNextMessageResponse) String() string { return proto.CompactTextString(m) }
func (*GetNextMessageResponse) ProtoMessage()    {}
func (*GetNextMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *GetNextMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNextMessageResponse.Unmarshal(m, b)
}
func (m *GetNextMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNextMessageResponse.Marshal(b, m, deterministic)
}
func (m *GetNextMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNextMessageResponse.Merge(m, src)
}
func (m *GetNextMessageResponse) XXX_Size() int {
	return xxx_messageInfo_GetNextMessageResponse.Size(m)
}
func (m *GetNextMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNextMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNextMessageResponse proto.InternalMessageInfo

func (m *GetNextMessageResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *GetNextMessageResponse) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type CreateTopicsRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTopicsRequest) Reset()         { *m = CreateTopicsRequest{} }
func (m *CreateTopicsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTopicsRequest) ProtoMessage()    {}
func (*CreateTopicsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *CreateTopicsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTopicsRequest.Unmarshal(m, b)
}
func (m *CreateTopicsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTopicsRequest.Marshal(b, m, deterministic)
}
func (m *CreateTopicsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTopicsRequest.Merge(m, src)
}
func (m *CreateTopicsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTopicsRequest.Size(m)
}
func (m *CreateTopicsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTopicsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTopicsRequest proto.InternalMessageInfo

func (m *CreateTopicsRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type CreateTopicsResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTopicsResponse) Reset()         { *m = CreateTopicsResponse{} }
func (m *CreateTopicsResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTopicsResponse) ProtoMessage()    {}
func (*CreateTopicsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *CreateTopicsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTopicsResponse.Unmarshal(m, b)
}
func (m *CreateTopicsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTopicsResponse.Marshal(b, m, deterministic)
}
func (m *CreateTopicsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTopicsResponse.Merge(m, src)
}
func (m *CreateTopicsResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTopicsResponse.Size(m)
}
func (m *CreateTopicsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTopicsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTopicsResponse proto.InternalMessageInfo

func (m *CreateTopicsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "api.Message")
	proto.RegisterMapType((map[string][]byte)(nil), "api.Message.MetaEntry")
	proto.RegisterType((*MessageWithRoute)(nil), "api.MessageWithRoute")
	proto.RegisterType((*MessagesBatchRequest)(nil), "api.MessagesBatchRequest")
	proto.RegisterType((*Error)(nil), "api.Error")
	proto.RegisterType((*MessagesBatchResponse)(nil), "api.MessagesBatchResponse")
	proto.RegisterMapType((map[string]uint64)(nil), "api.MessagesBatchResponse.ConsumedSeqsEntry")
	proto.RegisterMapType((map[string]uint64)(nil), "api.MessagesBatchResponse.ProducedSeqsEntry")
	proto.RegisterType((*GetLastMessageRequest)(nil), "api.GetLastMessageRequest")
	proto.RegisterType((*GetLastMessageResponse)(nil), "api.GetLastMessageResponse")
	proto.RegisterType((*GetNextMessageRequest)(nil), "api.GetNextMessageRequest")
	proto.RegisterType((*GetNextMessageResponse)(nil), "api.GetNextMessageResponse")
	proto.RegisterType((*CreateTopicsRequest)(nil), "api.CreateTopicsRequest")
	proto.RegisterType((*CreateTopicsResponse)(nil), "api.CreateTopicsResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xdf, 0x6a, 0x13, 0x41,
	0x14, 0xc6, 0xd9, 0x4d, 0x62, 0xcc, 0x49, 0x94, 0x3a, 0x26, 0x65, 0xbb, 0x7a, 0x11, 0xf6, 0xa2,
	0x04, 0xff, 0x04, 0x8c, 0x88, 0xc5, 0x9b, 0x42, 0x4a, 0x90, 0x82, 0x95, 0x30, 0x15, 0xbc, 0x9e,
	0x6e, 0x0e, 0x76, 0x69, 0x93, 0xd9, 0xcc, 0x4c, 0x8a, 0x79, 0x2b, 0x2f, 0x7d, 0x1b, 0x5f, 0x45,
	0x66, 0x76, 0x76, 0x33, 0xdb, 0x6c, 0x6d, 0x84, 0xde, 0xcd, 0x9f, 0x93, 0xdf, 0xf7, 0xed, 0xf9,
	0xce, 0x04, 0x5a, 0x2c, 0x4d, 0x86, 0xa9, 0xe0, 0x8a, 0x93, 0x1a, 0x4b, 0x93, 0xe8, 0xb7, 0x07,
	0xcd, 0x33, 0x94, 0x92, 0xfd, 0x40, 0xb2, 0x07, 0x35, 0x89, 0xcb, 0xc0, 0xeb, 0x7b, 0x83, 0x3a,
	0xd5, 0x4b, 0xf2, 0x12, 0x5a, 0x2a, 0x99, 0xa3, 0x54, 0x6c, 0x9e, 0x06, 0xbe, 0x39, 0xdf, 0x1c,
	0x90, 0x00, 0x9a, 0x29, 0x5b, 0x5f, 0x73, 0x36, 0x0b, 0x6a, 0x7d, 0x6f, 0xd0, 0xa1, 0xf9, 0x96,
	0xbc, 0x82, 0xfa, 0x1c, 0x15, 0x0b, 0xea, 0xfd, 0xda, 0xa0, 0x3d, 0xda, 0x1f, 0x6a, 0x51, 0xab,
	0x32, 0x3c, 0x43, 0xc5, 0x26, 0x0b, 0x25, 0xd6, 0xd4, 0xd4, 0x84, 0x1f, 0xa1, 0x55, 0x1c, 0x69,
	0x0b, 0x57, 0xb8, 0x36, 0x16, 0x5a, 0x54, 0x2f, 0x49, 0x17, 0x1a, 0x37, 0xec, 0x7a, 0x85, 0x46,
	0xbe, 0x43, 0xb3, 0xcd, 0x27, 0xff, 0xc8, 0x8b, 0xa6, 0xb0, 0x67, 0x99, 0xdf, 0x13, 0x75, 0x49,
	0xf9, 0x4a, 0x21, 0x39, 0x84, 0xe6, 0x3c, 0x3b, 0x33, 0x8c, 0xf6, 0xa8, 0xe3, 0x6a, 0xd3, 0xfc,
	0x52, 0x53, 0x15, 0x4f, 0x93, 0xd8, 0x50, 0x5b, 0x34, 0xdb, 0x44, 0xa7, 0xd0, 0xb5, 0x95, 0x72,
	0xcc, 0x54, 0x7c, 0x49, 0x71, 0xb9, 0x42, 0xa9, 0xc8, 0x3b, 0x78, 0x6c, 0x7f, 0x28, 0x03, 0xcf,
	0x7c, 0x52, 0xcf, 0xc5, 0x16, 0xf2, 0xb4, 0x28, 0x8b, 0x3e, 0x40, 0x63, 0x22, 0x04, 0x17, 0x84,
	0x40, 0x3d, 0xe6, 0x33, 0xb4, 0x5d, 0x35, 0x6b, 0xdd, 0xb8, 0xdc, 0x65, 0xa6, 0x9f, 0x6f, 0xa3,
	0x3f, 0x3e, 0xf4, 0x6e, 0x59, 0x90, 0x29, 0x5f, 0x48, 0x24, 0x7d, 0x68, 0xa0, 0x06, 0xda, 0xef,
	0x02, 0x63, 0xc0, 0x48, 0xd0, 0xec, 0x82, 0x4c, 0xa1, 0x13, 0xf3, 0x85, 0x5c, 0xcd, 0x71, 0x76,
	0x8e, 0x4b, 0x19, 0xf8, 0xc6, 0xe9, 0x1b, 0xd7, 0x69, 0x99, 0x39, 0x3c, 0x71, 0xca, 0xb3, 0x48,
	0x4a, 0x04, 0x4d, 0x4c, 0x05, 0x9f, 0xad, 0x62, 0x4b, 0xac, 0xdd, 0x4b, 0x9c, 0x3a, 0xe5, 0x96,
	0xe8, 0x12, 0xc2, 0x63, 0x78, 0xb6, 0x25, 0x7a, 0x5f, 0xe8, 0x75, 0x27, 0x74, 0x0d, 0xd8, 0xd2,
	0xf8, 0x1f, 0x40, 0xf4, 0x16, 0x7a, 0x9f, 0x51, 0x7d, 0x61, 0x52, 0xe5, 0x43, 0x61, 0x43, 0x2e,
	0x46, 0xc2, 0x73, 0x47, 0xe2, 0x02, 0xf6, 0x6f, 0x97, 0xef, 0x1c, 0xc8, 0x61, 0x39, 0xe6, 0xbb,
	0x86, 0x31, 0x3a, 0x36, 0x96, 0xbe, 0xe2, 0xcf, 0x9d, 0x2c, 0xe5, 0xcf, 0xd4, 0x2f, 0x9e, 0xa9,
	0x35, 0x59, 0x02, 0x3c, 0xb8, 0xc9, 0xd7, 0xf0, 0xfc, 0x44, 0x20, 0x53, 0xf8, 0x4d, 0x9b, 0x90,
	0xff, 0xee, 0xda, 0x11, 0x74, 0xcb, 0xc5, 0xbb, 0xda, 0x19, 0xfd, 0xf2, 0xe1, 0xc9, 0x58, 0xf0,
	0x2b, 0x14, 0xe7, 0x28, 0x6e, 0x92, 0x18, 0xc9, 0x04, 0x3a, 0x36, 0x71, 0x33, 0x6a, 0xe4, 0xa0,
	0x6a, 0xfc, 0x8c, 0x99, 0x30, 0xbc, 0x7b, 0x32, 0xc9, 0x29, 0x3c, 0x2d, 0x07, 0x49, 0xb2, 0xea,
	0xca, 0x61, 0x08, 0x5f, 0x54, 0xde, 0x95, 0x50, 0x4e, 0xbb, 0x37, 0xa8, 0xed, 0x10, 0x37, 0xa8,
	0xaa, 0x7c, 0xc6, 0xd0, 0x76, 0x1a, 0x45, 0x02, 0x53, 0x5b, 0xd1, 0xe7, 0xf0, 0xa0, 0xe2, 0x26,
	0x63, 0x5c, 0x3c, 0x32, 0x7f, 0xe7, 0xef, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x8d, 0x2f,
	0x39, 0xdb, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BrokerServiceClient is the client API for BrokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BrokerServiceClient interface {
	ProduceBatch(ctx context.Context, in *MessagesBatchRequest, opts ...grpc.CallOption) (*MessagesBatchResponse, error)
	GetLastMessage(ctx context.Context, in *GetLastMessageRequest, opts ...grpc.CallOption) (*GetLastMessageResponse, error)
	GetNextMessage(ctx context.Context, in *GetNextMessageRequest, opts ...grpc.CallOption) (*GetNextMessageResponse, error)
	CreateTopic(ctx context.Context, in *CreateTopicsRequest, opts ...grpc.CallOption) (*CreateTopicsResponse, error)
}

type brokerServiceClient struct {
	cc *grpc.ClientConn
}

func NewBrokerServiceClient(cc *grpc.ClientConn) BrokerServiceClient {
	return &brokerServiceClient{cc}
}

func (c *brokerServiceClient) ProduceBatch(ctx context.Context, in *MessagesBatchRequest, opts ...grpc.CallOption) (*MessagesBatchResponse, error) {
	out := new(MessagesBatchResponse)
	err := c.cc.Invoke(ctx, "/api.BrokerService/ProduceBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) GetLastMessage(ctx context.Context, in *GetLastMessageRequest, opts ...grpc.CallOption) (*GetLastMessageResponse, error) {
	out := new(GetLastMessageResponse)
	err := c.cc.Invoke(ctx, "/api.BrokerService/GetLastMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) GetNextMessage(ctx context.Context, in *GetNextMessageRequest, opts ...grpc.CallOption) (*GetNextMessageResponse, error) {
	out := new(GetNextMessageResponse)
	err := c.cc.Invoke(ctx, "/api.BrokerService/GetNextMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) CreateTopic(ctx context.Context, in *CreateTopicsRequest, opts ...grpc.CallOption) (*CreateTopicsResponse, error) {
	out := new(CreateTopicsResponse)
	err := c.cc.Invoke(ctx, "/api.BrokerService/CreateTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServiceServer is the server API for BrokerService service.
type BrokerServiceServer interface {
	ProduceBatch(context.Context, *MessagesBatchRequest) (*MessagesBatchResponse, error)
	GetLastMessage(context.Context, *GetLastMessageRequest) (*GetLastMessageResponse, error)
	GetNextMessage(context.Context, *GetNextMessageRequest) (*GetNextMessageResponse, error)
	CreateTopic(context.Context, *CreateTopicsRequest) (*CreateTopicsResponse, error)
}

// UnimplementedBrokerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBrokerServiceServer struct {
}

func (*UnimplementedBrokerServiceServer) ProduceBatch(ctx context.Context, req *MessagesBatchRequest) (*MessagesBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProduceBatch not implemented")
}
func (*UnimplementedBrokerServiceServer) GetLastMessage(ctx context.Context, req *GetLastMessageRequest) (*GetLastMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastMessage not implemented")
}
func (*UnimplementedBrokerServiceServer) GetNextMessage(ctx context.Context, req *GetNextMessageRequest) (*GetNextMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNextMessage not implemented")
}
func (*UnimplementedBrokerServiceServer) CreateTopic(ctx context.Context, req *CreateTopicsRequest) (*CreateTopicsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTopic not implemented")
}

func RegisterBrokerServiceServer(s *grpc.Server, srv BrokerServiceServer) {
	s.RegisterService(&_BrokerService_serviceDesc, srv)
}

func _BrokerService_ProduceBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagesBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).ProduceBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BrokerService/ProduceBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).ProduceBatch(ctx, req.(*MessagesBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_GetLastMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).GetLastMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BrokerService/GetLastMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).GetLastMessage(ctx, req.(*GetLastMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_GetNextMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNextMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).GetNextMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BrokerService/GetNextMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).GetNextMessage(ctx, req.(*GetNextMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_CreateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).CreateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BrokerService/CreateTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).CreateTopic(ctx, req.(*CreateTopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BrokerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.BrokerService",
	HandlerType: (*BrokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProduceBatch",
			Handler:    _BrokerService_ProduceBatch_Handler,
		},
		{
			MethodName: "GetLastMessage",
			Handler:    _BrokerService_GetLastMessage_Handler,
		},
		{
			MethodName: "GetNextMessage",
			Handler:    _BrokerService_GetNextMessage_Handler,
		},
		{
			MethodName: "CreateTopic",
			Handler:    _BrokerService_CreateTopic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
