// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Seq                  uint64            `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Timestamp            uint64            `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload              []byte            `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Meta                 map[string][]byte `protobuf:"bytes,4,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Message) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Message) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetMeta() map[string][]byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

type MessageWithRoute struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageWithRoute) Reset()         { *m = MessageWithRoute{} }
func (m *MessageWithRoute) String() string { return proto.CompactTextString(m) }
func (*MessageWithRoute) ProtoMessage()    {}
func (*MessageWithRoute) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *MessageWithRoute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithRoute.Unmarshal(m, b)
}
func (m *MessageWithRoute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithRoute.Marshal(b, m, deterministic)
}
func (m *MessageWithRoute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithRoute.Merge(m, src)
}
func (m *MessageWithRoute) XXX_Size() int {
	return xxx_messageInfo_MessageWithRoute.Size(m)
}
func (m *MessageWithRoute) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithRoute.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithRoute proto.InternalMessageInfo

func (m *MessageWithRoute) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *MessageWithRoute) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type Error struct {
	Code                 uint64            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 map[string]string `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type SendMessagesRequest struct {
	Messages             []*MessageWithRoute `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SendMessagesRequest) Reset()         { *m = SendMessagesRequest{} }
func (m *SendMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessagesRequest) ProtoMessage()    {}
func (*SendMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *SendMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessagesRequest.Unmarshal(m, b)
}
func (m *SendMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessagesRequest.Marshal(b, m, deterministic)
}
func (m *SendMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessagesRequest.Merge(m, src)
}
func (m *SendMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessagesRequest.Size(m)
}
func (m *SendMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessagesRequest proto.InternalMessageInfo

func (m *SendMessagesRequest) GetMessages() []*MessageWithRoute {
	if m != nil {
		return m.Messages
	}
	return nil
}

type SendMessagesResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessagesResponse) Reset()         { *m = SendMessagesResponse{} }
func (m *SendMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*SendMessagesResponse) ProtoMessage()    {}
func (*SendMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *SendMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessagesResponse.Unmarshal(m, b)
}
func (m *SendMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessagesResponse.Marshal(b, m, deterministic)
}
func (m *SendMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessagesResponse.Merge(m, src)
}
func (m *SendMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_SendMessagesResponse.Size(m)
}
func (m *SendMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessagesResponse proto.InternalMessageInfo

func (m *SendMessagesResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type RecieveMessagesRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Seq                  uint64   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	MaxBatch             uint32   `protobuf:"varint,3,opt,name=maxBatch,proto3" json:"maxBatch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecieveMessagesRequest) Reset()         { *m = RecieveMessagesRequest{} }
func (m *RecieveMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*RecieveMessagesRequest) ProtoMessage()    {}
func (*RecieveMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *RecieveMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecieveMessagesRequest.Unmarshal(m, b)
}
func (m *RecieveMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecieveMessagesRequest.Marshal(b, m, deterministic)
}
func (m *RecieveMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecieveMessagesRequest.Merge(m, src)
}
func (m *RecieveMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_RecieveMessagesRequest.Size(m)
}
func (m *RecieveMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecieveMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecieveMessagesRequest proto.InternalMessageInfo

func (m *RecieveMessagesRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *RecieveMessagesRequest) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *RecieveMessagesRequest) GetMaxBatch() uint32 {
	if m != nil {
		return m.MaxBatch
	}
	return 0
}

type RecieveMessagesResponse struct {
	Error                *Error     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Messages             []*Message `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RecieveMessagesResponse) Reset()         { *m = RecieveMessagesResponse{} }
func (m *RecieveMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*RecieveMessagesResponse) ProtoMessage()    {}
func (*RecieveMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *RecieveMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecieveMessagesResponse.Unmarshal(m, b)
}
func (m *RecieveMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecieveMessagesResponse.Marshal(b, m, deterministic)
}
func (m *RecieveMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecieveMessagesResponse.Merge(m, src)
}
func (m *RecieveMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_RecieveMessagesResponse.Size(m)
}
func (m *RecieveMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecieveMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecieveMessagesResponse proto.InternalMessageInfo

func (m *RecieveMessagesResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *RecieveMessagesResponse) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type GetLastMessageRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLastMessageRequest) Reset()         { *m = GetLastMessageRequest{} }
func (m *GetLastMessageRequest) String() string { return proto.CompactTextString(m) }
func (*GetLastMessageRequest) ProtoMessage()    {}
func (*GetLastMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *GetLastMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLastMessageRequest.Unmarshal(m, b)
}
func (m *GetLastMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLastMessageRequest.Marshal(b, m, deterministic)
}
func (m *GetLastMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLastMessageRequest.Merge(m, src)
}
func (m *GetLastMessageRequest) XXX_Size() int {
	return xxx_messageInfo_GetLastMessageRequest.Size(m)
}
func (m *GetLastMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLastMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLastMessageRequest proto.InternalMessageInfo

func (m *GetLastMessageRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type GetLastMessageResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Message              *Message `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLastMessageResponse) Reset()         { *m = GetLastMessageResponse{} }
func (m *GetLastMessageResponse) String() string { return proto.CompactTextString(m) }
func (*GetLastMessageResponse) ProtoMessage()    {}
func (*GetLastMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *GetLastMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLastMessageResponse.Unmarshal(m, b)
}
func (m *GetLastMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLastMessageResponse.Marshal(b, m, deterministic)
}
func (m *GetLastMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLastMessageResponse.Merge(m, src)
}
func (m *GetLastMessageResponse) XXX_Size() int {
	return xxx_messageInfo_GetLastMessageResponse.Size(m)
}
func (m *GetLastMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLastMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLastMessageResponse proto.InternalMessageInfo

func (m *GetLastMessageResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *GetLastMessageResponse) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type CreateTopicsRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTopicsRequest) Reset()         { *m = CreateTopicsRequest{} }
func (m *CreateTopicsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTopicsRequest) ProtoMessage()    {}
func (*CreateTopicsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *CreateTopicsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTopicsRequest.Unmarshal(m, b)
}
func (m *CreateTopicsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTopicsRequest.Marshal(b, m, deterministic)
}
func (m *CreateTopicsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTopicsRequest.Merge(m, src)
}
func (m *CreateTopicsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTopicsRequest.Size(m)
}
func (m *CreateTopicsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTopicsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTopicsRequest proto.InternalMessageInfo

func (m *CreateTopicsRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type CreateTopicsResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTopicsResponse) Reset()         { *m = CreateTopicsResponse{} }
func (m *CreateTopicsResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTopicsResponse) ProtoMessage()    {}
func (*CreateTopicsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *CreateTopicsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTopicsResponse.Unmarshal(m, b)
}
func (m *CreateTopicsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTopicsResponse.Marshal(b, m, deterministic)
}
func (m *CreateTopicsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTopicsResponse.Merge(m, src)
}
func (m *CreateTopicsResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTopicsResponse.Size(m)
}
func (m *CreateTopicsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTopicsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTopicsResponse proto.InternalMessageInfo

func (m *CreateTopicsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type RecieveMetaRequest struct {
	Topics               []string `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecieveMetaRequest) Reset()         { *m = RecieveMetaRequest{} }
func (m *RecieveMetaRequest) String() string { return proto.CompactTextString(m) }
func (*RecieveMetaRequest) ProtoMessage()    {}
func (*RecieveMetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *RecieveMetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecieveMetaRequest.Unmarshal(m, b)
}
func (m *RecieveMetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecieveMetaRequest.Marshal(b, m, deterministic)
}
func (m *RecieveMetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecieveMetaRequest.Merge(m, src)
}
func (m *RecieveMetaRequest) XXX_Size() int {
	return xxx_messageInfo_RecieveMetaRequest.Size(m)
}
func (m *RecieveMetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecieveMetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecieveMetaRequest proto.InternalMessageInfo

func (m *RecieveMetaRequest) GetTopics() []string {
	if m != nil {
		return m.Topics
	}
	return nil
}

type RecieveMetaResponse struct {
	Error                *Error            `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ConsumedSeqs         map[string]uint64 `protobuf:"bytes,2,rep,name=consumedSeqs,proto3" json:"consumedSeqs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	ProducedSeqs         map[string]uint64 `protobuf:"bytes,3,rep,name=producedSeqs,proto3" json:"producedSeqs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	StoredSeqs           map[string]uint64 `protobuf:"bytes,4,rep,name=storedSeqs,proto3" json:"storedSeqs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	AvailableSeqs        map[string]uint64 `protobuf:"bytes,5,rep,name=availableSeqs,proto3" json:"availableSeqs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RecieveMetaResponse) Reset()         { *m = RecieveMetaResponse{} }
func (m *RecieveMetaResponse) String() string { return proto.CompactTextString(m) }
func (*RecieveMetaResponse) ProtoMessage()    {}
func (*RecieveMetaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *RecieveMetaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecieveMetaResponse.Unmarshal(m, b)
}
func (m *RecieveMetaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecieveMetaResponse.Marshal(b, m, deterministic)
}
func (m *RecieveMetaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecieveMetaResponse.Merge(m, src)
}
func (m *RecieveMetaResponse) XXX_Size() int {
	return xxx_messageInfo_RecieveMetaResponse.Size(m)
}
func (m *RecieveMetaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecieveMetaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecieveMetaResponse proto.InternalMessageInfo

func (m *RecieveMetaResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *RecieveMetaResponse) GetConsumedSeqs() map[string]uint64 {
	if m != nil {
		return m.ConsumedSeqs
	}
	return nil
}

func (m *RecieveMetaResponse) GetProducedSeqs() map[string]uint64 {
	if m != nil {
		return m.ProducedSeqs
	}
	return nil
}

func (m *RecieveMetaResponse) GetStoredSeqs() map[string]uint64 {
	if m != nil {
		return m.StoredSeqs
	}
	return nil
}

func (m *RecieveMetaResponse) GetAvailableSeqs() map[string]uint64 {
	if m != nil {
		return m.AvailableSeqs
	}
	return nil
}

type SendConsumerMetaRequest struct {
	ConsumerID           string            `protobuf:"bytes,1,opt,name=consumerID,proto3" json:"consumerID,omitempty"`
	ConsumedSeqs         map[string]uint64 `protobuf:"bytes,2,rep,name=consumedSeqs,proto3" json:"consumedSeqs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SendConsumerMetaRequest) Reset()         { *m = SendConsumerMetaRequest{} }
func (m *SendConsumerMetaRequest) String() string { return proto.CompactTextString(m) }
func (*SendConsumerMetaRequest) ProtoMessage()    {}
func (*SendConsumerMetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *SendConsumerMetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendConsumerMetaRequest.Unmarshal(m, b)
}
func (m *SendConsumerMetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendConsumerMetaRequest.Marshal(b, m, deterministic)
}
func (m *SendConsumerMetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendConsumerMetaRequest.Merge(m, src)
}
func (m *SendConsumerMetaRequest) XXX_Size() int {
	return xxx_messageInfo_SendConsumerMetaRequest.Size(m)
}
func (m *SendConsumerMetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendConsumerMetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendConsumerMetaRequest proto.InternalMessageInfo

func (m *SendConsumerMetaRequest) GetConsumerID() string {
	if m != nil {
		return m.ConsumerID
	}
	return ""
}

func (m *SendConsumerMetaRequest) GetConsumedSeqs() map[string]uint64 {
	if m != nil {
		return m.ConsumedSeqs
	}
	return nil
}

type SendProducerMetaRequest struct {
	ProducedSeqs         map[string]uint64 `protobuf:"bytes,1,rep,name=producedSeqs,proto3" json:"producedSeqs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SendProducerMetaRequest) Reset()         { *m = SendProducerMetaRequest{} }
func (m *SendProducerMetaRequest) String() string { return proto.CompactTextString(m) }
func (*SendProducerMetaRequest) ProtoMessage()    {}
func (*SendProducerMetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *SendProducerMetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendProducerMetaRequest.Unmarshal(m, b)
}
func (m *SendProducerMetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendProducerMetaRequest.Marshal(b, m, deterministic)
}
func (m *SendProducerMetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendProducerMetaRequest.Merge(m, src)
}
func (m *SendProducerMetaRequest) XXX_Size() int {
	return xxx_messageInfo_SendProducerMetaRequest.Size(m)
}
func (m *SendProducerMetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendProducerMetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendProducerMetaRequest proto.InternalMessageInfo

func (m *SendProducerMetaRequest) GetProducedSeqs() map[string]uint64 {
	if m != nil {
		return m.ProducedSeqs
	}
	return nil
}

type SendMetaResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMetaResponse) Reset()         { *m = SendMetaResponse{} }
func (m *SendMetaResponse) String() string { return proto.CompactTextString(m) }
func (*SendMetaResponse) ProtoMessage()    {}
func (*SendMetaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *SendMetaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMetaResponse.Unmarshal(m, b)
}
func (m *SendMetaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMetaResponse.Marshal(b, m, deterministic)
}
func (m *SendMetaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMetaResponse.Merge(m, src)
}
func (m *SendMetaResponse) XXX_Size() int {
	return xxx_messageInfo_SendMetaResponse.Size(m)
}
func (m *SendMetaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMetaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMetaResponse proto.InternalMessageInfo

func (m *SendMetaResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type CreateConsumerRequest struct {
	ConsumerID           string   `protobuf:"bytes,1,opt,name=consumerID,proto3" json:"consumerID,omitempty"`
	Topics               []string `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	AttachStrategy       string   `protobuf:"bytes,3,opt,name=attachStrategy,proto3" json:"attachStrategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateConsumerRequest) Reset()         { *m = CreateConsumerRequest{} }
func (m *CreateConsumerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateConsumerRequest) ProtoMessage()    {}
func (*CreateConsumerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{16}
}

func (m *CreateConsumerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConsumerRequest.Unmarshal(m, b)
}
func (m *CreateConsumerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConsumerRequest.Marshal(b, m, deterministic)
}
func (m *CreateConsumerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConsumerRequest.Merge(m, src)
}
func (m *CreateConsumerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateConsumerRequest.Size(m)
}
func (m *CreateConsumerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConsumerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConsumerRequest proto.InternalMessageInfo

func (m *CreateConsumerRequest) GetConsumerID() string {
	if m != nil {
		return m.ConsumerID
	}
	return ""
}

func (m *CreateConsumerRequest) GetTopics() []string {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *CreateConsumerRequest) GetAttachStrategy() string {
	if m != nil {
		return m.AttachStrategy
	}
	return ""
}

type CreateConsumerResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateConsumerResponse) Reset()         { *m = CreateConsumerResponse{} }
func (m *CreateConsumerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateConsumerResponse) ProtoMessage()    {}
func (*CreateConsumerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{17}
}

func (m *CreateConsumerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConsumerResponse.Unmarshal(m, b)
}
func (m *CreateConsumerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConsumerResponse.Marshal(b, m, deterministic)
}
func (m *CreateConsumerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConsumerResponse.Merge(m, src)
}
func (m *CreateConsumerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateConsumerResponse.Size(m)
}
func (m *CreateConsumerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConsumerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConsumerResponse proto.InternalMessageInfo

func (m *CreateConsumerResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "api.Message")
	proto.RegisterMapType((map[string][]byte)(nil), "api.Message.MetaEntry")
	proto.RegisterType((*MessageWithRoute)(nil), "api.MessageWithRoute")
	proto.RegisterType((*Error)(nil), "api.Error")
	proto.RegisterMapType((map[string]string)(nil), "api.Error.DataEntry")
	proto.RegisterType((*SendMessagesRequest)(nil), "api.SendMessagesRequest")
	proto.RegisterType((*SendMessagesResponse)(nil), "api.SendMessagesResponse")
	proto.RegisterType((*RecieveMessagesRequest)(nil), "api.RecieveMessagesRequest")
	proto.RegisterType((*RecieveMessagesResponse)(nil), "api.RecieveMessagesResponse")
	proto.RegisterType((*GetLastMessageRequest)(nil), "api.GetLastMessageRequest")
	proto.RegisterType((*GetLastMessageResponse)(nil), "api.GetLastMessageResponse")
	proto.RegisterType((*CreateTopicsRequest)(nil), "api.CreateTopicsRequest")
	proto.RegisterType((*CreateTopicsResponse)(nil), "api.CreateTopicsResponse")
	proto.RegisterType((*RecieveMetaRequest)(nil), "api.RecieveMetaRequest")
	proto.RegisterType((*RecieveMetaResponse)(nil), "api.RecieveMetaResponse")
	proto.RegisterMapType((map[string]uint64)(nil), "api.RecieveMetaResponse.AvailableSeqsEntry")
	proto.RegisterMapType((map[string]uint64)(nil), "api.RecieveMetaResponse.ConsumedSeqsEntry")
	proto.RegisterMapType((map[string]uint64)(nil), "api.RecieveMetaResponse.ProducedSeqsEntry")
	proto.RegisterMapType((map[string]uint64)(nil), "api.RecieveMetaResponse.StoredSeqsEntry")
	proto.RegisterType((*SendConsumerMetaRequest)(nil), "api.SendConsumerMetaRequest")
	proto.RegisterMapType((map[string]uint64)(nil), "api.SendConsumerMetaRequest.ConsumedSeqsEntry")
	proto.RegisterType((*SendProducerMetaRequest)(nil), "api.SendProducerMetaRequest")
	proto.RegisterMapType((map[string]uint64)(nil), "api.SendProducerMetaRequest.ProducedSeqsEntry")
	proto.RegisterType((*SendMetaResponse)(nil), "api.SendMetaResponse")
	proto.RegisterType((*CreateConsumerRequest)(nil), "api.CreateConsumerRequest")
	proto.RegisterType((*CreateConsumerResponse)(nil), "api.CreateConsumerResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 836 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x4e, 0xdb, 0x4a,
	0x10, 0x96, 0x13, 0x07, 0xf0, 0x24, 0xfc, 0x9c, 0x85, 0x04, 0x9f, 0x80, 0x8e, 0x22, 0x5f, 0xa0,
	0x08, 0xce, 0x89, 0x74, 0x38, 0x47, 0x2a, 0x42, 0xaa, 0x4a, 0xf9, 0x11, 0x20, 0x41, 0x45, 0x37,
	0x95, 0x7a, 0xd3, 0x9b, 0xc5, 0x19, 0x81, 0x45, 0x12, 0x1b, 0x7b, 0x93, 0x36, 0x37, 0x7d, 0xa4,
	0x5e, 0xf7, 0x29, 0xaa, 0xbe, 0x4d, 0x6f, 0x2b, 0xaf, 0x37, 0xce, 0xda, 0x71, 0xfe, 0xc4, 0x9d,
	0x77, 0x77, 0xf6, 0x9b, 0xf9, 0x66, 0xbe, 0x9d, 0x31, 0x18, 0xcc, 0x73, 0x1a, 0x9e, 0xef, 0x72,
	0x97, 0xe4, 0x99, 0xe7, 0x58, 0xdf, 0x35, 0x58, 0xbe, 0xc5, 0x20, 0x60, 0x0f, 0x48, 0x36, 0x20,
	0x1f, 0xe0, 0xb3, 0xa9, 0xd5, 0xb4, 0xba, 0x4e, 0xc3, 0x4f, 0xb2, 0x0b, 0x06, 0x77, 0x3a, 0x18,
	0x70, 0xd6, 0xf1, 0xcc, 0x9c, 0xd8, 0x1f, 0x6d, 0x10, 0x13, 0x96, 0x3d, 0x36, 0x68, 0xbb, 0xac,
	0x65, 0xe6, 0x6b, 0x5a, 0xbd, 0x44, 0x87, 0x4b, 0xb2, 0x0f, 0x7a, 0x07, 0x39, 0x33, 0xf5, 0x5a,
	0xbe, 0x5e, 0x3c, 0xac, 0x34, 0x42, 0xa7, 0xd2, 0x4b, 0xe3, 0x16, 0x39, 0xbb, 0xe8, 0x72, 0x7f,
	0x40, 0x85, 0x4d, 0xf5, 0x15, 0x18, 0xf1, 0x56, 0x18, 0xc2, 0x13, 0x0e, 0x44, 0x08, 0x06, 0x0d,
	0x3f, 0xc9, 0x16, 0x14, 0xfa, 0xac, 0xdd, 0x43, 0xe1, 0xbe, 0x44, 0xa3, 0xc5, 0x71, 0xee, 0x48,
	0xb3, 0xee, 0x60, 0x43, 0x62, 0x7e, 0x74, 0xf8, 0x23, 0x75, 0x7b, 0x1c, 0xc9, 0x1e, 0x2c, 0x77,
	0xa2, 0x3d, 0x81, 0x51, 0x3c, 0x2c, 0xa9, 0xbe, 0xe9, 0xf0, 0x30, 0x44, 0xe5, 0xae, 0xe7, 0xd8,
	0x02, 0xd5, 0xa0, 0xd1, 0xc2, 0xfa, 0x0a, 0x85, 0x0b, 0xdf, 0x77, 0x7d, 0x42, 0x40, 0xb7, 0xdd,
	0x16, 0xca, 0x54, 0x88, 0x6f, 0x52, 0x07, 0xbd, 0xc5, 0x38, 0x33, 0x73, 0x82, 0xd3, 0x96, 0xc0,
	0x15, 0xd6, 0x8d, 0x73, 0x16, 0x33, 0x0a, 0x2d, 0x42, 0x46, 0xf1, 0xd6, 0x2c, 0x46, 0x86, 0xca,
	0xe8, 0x0a, 0x36, 0x9b, 0xd8, 0x6d, 0xc9, 0x68, 0x03, 0x8a, 0xcf, 0x3d, 0x0c, 0x38, 0xf9, 0x17,
	0x56, 0x64, 0xdc, 0x81, 0xa9, 0x09, 0xef, 0x65, 0x95, 0x55, 0xcc, 0x9e, 0xc6, 0x66, 0xd6, 0x11,
	0x6c, 0x25, 0x91, 0x02, 0xcf, 0xed, 0x06, 0x48, 0x6a, 0x50, 0xc0, 0x30, 0x66, 0x99, 0x1d, 0x18,
	0xb1, 0xa0, 0xd1, 0x81, 0xf5, 0x09, 0x2a, 0x14, 0x6d, 0x07, 0xfb, 0x98, 0x0e, 0x23, 0xce, 0x99,
	0xa6, 0xe4, 0x6c, 0x28, 0x9a, 0xdc, 0x48, 0x34, 0x55, 0x58, 0xe9, 0xb0, 0x2f, 0xa7, 0x8c, 0xdb,
	0x8f, 0x42, 0x17, 0xab, 0x34, 0x5e, 0x5b, 0x08, 0xdb, 0x63, 0xe8, 0xf3, 0x86, 0x46, 0xea, 0x4a,
	0x1e, 0xa2, 0x2a, 0x24, 0xab, 0x3b, 0xa2, 0xff, 0x0f, 0x94, 0x2f, 0x91, 0xdf, 0xb0, 0x80, 0x0f,
	0xcf, 0xa6, 0x71, 0xb0, 0xee, 0xa1, 0x92, 0x36, 0x9f, 0x3b, 0x28, 0x45, 0x71, 0xb9, 0x29, 0x8a,
	0xb3, 0x0e, 0x60, 0xf3, 0xcc, 0x47, 0xc6, 0xf1, 0x43, 0xe8, 0x72, 0x7a, 0x52, 0xc3, 0xf2, 0x25,
	0x8d, 0xe7, 0x2e, 0xdf, 0xdf, 0x40, 0xe2, 0x04, 0x73, 0x36, 0xf4, 0x52, 0x81, 0x25, 0x01, 0x1c,
	0xe9, 0xc7, 0xa0, 0x72, 0x65, 0xfd, 0xd2, 0x61, 0x33, 0x61, 0x3e, 0x37, 0xed, 0x77, 0x50, 0xb2,
	0xdd, 0x6e, 0xd0, 0xeb, 0x60, 0xab, 0x89, 0xcf, 0xc3, 0x7a, 0xec, 0x0b, 0xc3, 0x0c, 0xc4, 0xc6,
	0x99, 0x62, 0x1c, 0xbd, 0x95, 0xc4, 0xfd, 0x10, 0xcf, 0xf3, 0xdd, 0x56, 0xcf, 0x96, 0x78, 0xf9,
	0x19, 0x78, 0x77, 0x8a, 0xb1, 0xc4, 0x53, 0xef, 0x93, 0x2b, 0x80, 0x80, 0xbb, 0xbe, 0x44, 0x8b,
	0xfa, 0x50, 0x7d, 0x22, 0x5a, 0x33, 0x36, 0x8d, 0xb0, 0x94, 0xbb, 0xe4, 0x3d, 0xac, 0xb2, 0x3e,
	0x73, 0xda, 0xec, 0xbe, 0x8d, 0x02, 0xac, 0x20, 0xc0, 0x0e, 0x26, 0x82, 0xbd, 0x55, 0xad, 0x23,
	0xbc, 0x24, 0x42, 0xf5, 0x0d, 0xfc, 0x31, 0x96, 0x8f, 0x59, 0x8d, 0x42, 0x57, 0x1a, 0x45, 0x08,
	0x30, 0x96, 0x80, 0x85, 0x00, 0x5e, 0xc3, 0x7a, 0x8a, 0xf3, 0x42, 0xd7, 0x4f, 0x80, 0x8c, 0xb3,
	0x5c, 0x04, 0xc1, 0xfa, 0xa1, 0xc1, 0x76, 0xd8, 0xa1, 0x64, 0x1e, 0x7c, 0x55, 0xad, 0x7f, 0x01,
	0x48, 0x6d, 0xf8, 0xd7, 0xe7, 0x12, 0x4e, 0xd9, 0x21, 0x34, 0x53, 0x7b, 0x0d, 0x51, 0x90, 0x09,
	0x98, 0xb3, 0xf4, 0xf7, 0xe2, 0x92, 0x58, 0xdf, 0x24, 0x21, 0x59, 0x97, 0x04, 0x21, 0x9a, 0x12,
	0xb7, 0x96, 0x0a, 0x38, 0xe3, 0xce, 0x2c, 0x81, 0xbf, 0x58, 0x02, 0xd6, 0xff, 0xb0, 0x11, 0x8d,
	0x88, 0x45, 0xde, 0xbd, 0xf5, 0x19, 0xca, 0x51, 0x67, 0x1a, 0x26, 0x79, 0xde, 0xa2, 0x8d, 0x5a,
	0x50, 0x4e, 0x6d, 0x41, 0x64, 0x0f, 0xd6, 0x18, 0xe7, 0xcc, 0x7e, 0x6c, 0x72, 0x9f, 0x71, 0x7c,
	0x18, 0x88, 0x99, 0x61, 0xd0, 0xd4, 0xae, 0x75, 0x0c, 0x95, 0xb4, 0xe3, 0x79, 0x83, 0x3e, 0xfc,
	0xa9, 0xc3, 0xea, 0xa9, 0xef, 0x3e, 0xa1, 0xdf, 0x44, 0xbf, 0xef, 0xd8, 0x48, 0xce, 0xa0, 0xa4,
	0xce, 0x47, 0x62, 0xc6, 0xb5, 0x48, 0x4d, 0xbd, 0xea, 0x9f, 0x19, 0x27, 0xd2, 0xf1, 0x35, 0xac,
	0x25, 0xc7, 0x06, 0xa9, 0x0a, 0xe3, 0xcc, 0xd1, 0x53, 0xdd, 0xc9, 0x3c, 0x93, 0x50, 0xa7, 0x50,
	0x54, 0x1a, 0xbe, 0x0c, 0x27, 0x63, 0x5e, 0xc8, 0x70, 0x32, 0x87, 0xc3, 0x65, 0x54, 0x50, 0x55,
	0x4c, 0x64, 0x77, 0x9a, 0xc6, 0xaa, 0x65, 0x85, 0x9b, 0xa2, 0x82, 0x1b, 0x58, 0x4f, 0x0d, 0x69,
	0xb2, 0x93, 0xec, 0x76, 0xc9, 0x14, 0xed, 0x66, 0x1f, 0x26, 0xc3, 0x52, 0x1f, 0xa5, 0x12, 0x56,
	0xc6, 0x5b, 0x9d, 0x14, 0xd6, 0x35, 0xac, 0x25, 0x15, 0x20, 0xd3, 0x9d, 0xa9, 0x47, 0x99, 0xee,
	0x09, 0x92, 0x39, 0x81, 0xa2, 0xd2, 0xb9, 0xc9, 0xf6, 0x78, 0x2f, 0x8f, 0x40, 0xcc, 0x49, 0x4d,
	0xfe, 0x7e, 0x49, 0xfc, 0x43, 0xff, 0xf7, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x79, 0x84, 0x7f, 0x2c,
	0x50, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BrokerServiceClient is the client API for BrokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BrokerServiceClient interface {
	// ProducerAPI
	SendMessages(ctx context.Context, in *SendMessagesRequest, opts ...grpc.CallOption) (*SendMessagesResponse, error)
	GetLastMessage(ctx context.Context, in *GetLastMessageRequest, opts ...grpc.CallOption) (*GetLastMessageResponse, error)
	CreateTopic(ctx context.Context, in *CreateTopicsRequest, opts ...grpc.CallOption) (*CreateTopicsResponse, error)
	SendProducerMeta(ctx context.Context, in *SendProducerMetaRequest, opts ...grpc.CallOption) (*SendMetaResponse, error)
	// ConsumerAPI
	RecieveMessages(ctx context.Context, in *RecieveMessagesRequest, opts ...grpc.CallOption) (*RecieveMessagesResponse, error)
	SendConsumerMeta(ctx context.Context, in *SendConsumerMetaRequest, opts ...grpc.CallOption) (*SendMetaResponse, error)
	CreateConsumer(ctx context.Context, in *CreateConsumerRequest, opts ...grpc.CallOption) (*CreateConsumerResponse, error)
	// CommonAPI
	RecieveMeta(ctx context.Context, in *RecieveMetaRequest, opts ...grpc.CallOption) (*RecieveMetaResponse, error)
}

type brokerServiceClient struct {
	cc *grpc.ClientConn
}

func NewBrokerServiceClient(cc *grpc.ClientConn) BrokerServiceClient {
	return &brokerServiceClient{cc}
}

func (c *brokerServiceClient) SendMessages(ctx context.Context, in *SendMessagesRequest, opts ...grpc.CallOption) (*SendMessagesResponse, error) {
	out := new(SendMessagesResponse)
	err := c.cc.Invoke(ctx, "/api.BrokerService/SendMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) GetLastMessage(ctx context.Context, in *GetLastMessageRequest, opts ...grpc.CallOption) (*GetLastMessageResponse, error) {
	out := new(GetLastMessageResponse)
	err := c.cc.Invoke(ctx, "/api.BrokerService/GetLastMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) CreateTopic(ctx context.Context, in *CreateTopicsRequest, opts ...grpc.CallOption) (*CreateTopicsResponse, error) {
	out := new(CreateTopicsResponse)
	err := c.cc.Invoke(ctx, "/api.BrokerService/CreateTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) SendProducerMeta(ctx context.Context, in *SendProducerMetaRequest, opts ...grpc.CallOption) (*SendMetaResponse, error) {
	out := new(SendMetaResponse)
	err := c.cc.Invoke(ctx, "/api.BrokerService/SendProducerMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) RecieveMessages(ctx context.Context, in *RecieveMessagesRequest, opts ...grpc.CallOption) (*RecieveMessagesResponse, error) {
	out := new(RecieveMessagesResponse)
	err := c.cc.Invoke(ctx, "/api.BrokerService/RecieveMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) SendConsumerMeta(ctx context.Context, in *SendConsumerMetaRequest, opts ...grpc.CallOption) (*SendMetaResponse, error) {
	out := new(SendMetaResponse)
	err := c.cc.Invoke(ctx, "/api.BrokerService/SendConsumerMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) CreateConsumer(ctx context.Context, in *CreateConsumerRequest, opts ...grpc.CallOption) (*CreateConsumerResponse, error) {
	out := new(CreateConsumerResponse)
	err := c.cc.Invoke(ctx, "/api.BrokerService/CreateConsumer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) RecieveMeta(ctx context.Context, in *RecieveMetaRequest, opts ...grpc.CallOption) (*RecieveMetaResponse, error) {
	out := new(RecieveMetaResponse)
	err := c.cc.Invoke(ctx, "/api.BrokerService/RecieveMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServiceServer is the server API for BrokerService service.
type BrokerServiceServer interface {
	// ProducerAPI
	SendMessages(context.Context, *SendMessagesRequest) (*SendMessagesResponse, error)
	GetLastMessage(context.Context, *GetLastMessageRequest) (*GetLastMessageResponse, error)
	CreateTopic(context.Context, *CreateTopicsRequest) (*CreateTopicsResponse, error)
	SendProducerMeta(context.Context, *SendProducerMetaRequest) (*SendMetaResponse, error)
	// ConsumerAPI
	RecieveMessages(context.Context, *RecieveMessagesRequest) (*RecieveMessagesResponse, error)
	SendConsumerMeta(context.Context, *SendConsumerMetaRequest) (*SendMetaResponse, error)
	CreateConsumer(context.Context, *CreateConsumerRequest) (*CreateConsumerResponse, error)
	// CommonAPI
	RecieveMeta(context.Context, *RecieveMetaRequest) (*RecieveMetaResponse, error)
}

// UnimplementedBrokerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBrokerServiceServer struct {
}

func (*UnimplementedBrokerServiceServer) SendMessages(ctx context.Context, req *SendMessagesRequest) (*SendMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessages not implemented")
}
func (*UnimplementedBrokerServiceServer) GetLastMessage(ctx context.Context, req *GetLastMessageRequest) (*GetLastMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastMessage not implemented")
}
func (*UnimplementedBrokerServiceServer) CreateTopic(ctx context.Context, req *CreateTopicsRequest) (*CreateTopicsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTopic not implemented")
}
func (*UnimplementedBrokerServiceServer) SendProducerMeta(ctx context.Context, req *SendProducerMetaRequest) (*SendMetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendProducerMeta not implemented")
}
func (*UnimplementedBrokerServiceServer) RecieveMessages(ctx context.Context, req *RecieveMessagesRequest) (*RecieveMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecieveMessages not implemented")
}
func (*UnimplementedBrokerServiceServer) SendConsumerMeta(ctx context.Context, req *SendConsumerMetaRequest) (*SendMetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendConsumerMeta not implemented")
}
func (*UnimplementedBrokerServiceServer) CreateConsumer(ctx context.Context, req *CreateConsumerRequest) (*CreateConsumerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConsumer not implemented")
}
func (*UnimplementedBrokerServiceServer) RecieveMeta(ctx context.Context, req *RecieveMetaRequest) (*RecieveMetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecieveMeta not implemented")
}

func RegisterBrokerServiceServer(s *grpc.Server, srv BrokerServiceServer) {
	s.RegisterService(&_BrokerService_serviceDesc, srv)
}

func _BrokerService_SendMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).SendMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BrokerService/SendMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).SendMessages(ctx, req.(*SendMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_GetLastMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).GetLastMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BrokerService/GetLastMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).GetLastMessage(ctx, req.(*GetLastMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_CreateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).CreateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BrokerService/CreateTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).CreateTopic(ctx, req.(*CreateTopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_SendProducerMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendProducerMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).SendProducerMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BrokerService/SendProducerMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).SendProducerMeta(ctx, req.(*SendProducerMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_RecieveMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecieveMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).RecieveMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BrokerService/RecieveMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).RecieveMessages(ctx, req.(*RecieveMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_SendConsumerMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendConsumerMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).SendConsumerMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BrokerService/SendConsumerMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).SendConsumerMeta(ctx, req.(*SendConsumerMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_CreateConsumer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConsumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).CreateConsumer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BrokerService/CreateConsumer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).CreateConsumer(ctx, req.(*CreateConsumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_RecieveMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecieveMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).RecieveMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BrokerService/RecieveMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).RecieveMeta(ctx, req.(*RecieveMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BrokerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.BrokerService",
	HandlerType: (*BrokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessages",
			Handler:    _BrokerService_SendMessages_Handler,
		},
		{
			MethodName: "GetLastMessage",
			Handler:    _BrokerService_GetLastMessage_Handler,
		},
		{
			MethodName: "CreateTopic",
			Handler:    _BrokerService_CreateTopic_Handler,
		},
		{
			MethodName: "SendProducerMeta",
			Handler:    _BrokerService_SendProducerMeta_Handler,
		},
		{
			MethodName: "RecieveMessages",
			Handler:    _BrokerService_RecieveMessages_Handler,
		},
		{
			MethodName: "SendConsumerMeta",
			Handler:    _BrokerService_SendConsumerMeta_Handler,
		},
		{
			MethodName: "CreateConsumer",
			Handler:    _BrokerService_CreateConsumer_Handler,
		},
		{
			MethodName: "RecieveMeta",
			Handler:    _BrokerService_RecieveMeta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
